package com.next.model;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_short_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_category
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_kind1
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemKind1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_kind2
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemKind2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_kind3
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemKind3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_detail
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.insert_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.insert_datetime
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Date insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_datetime
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_id
     *
     * @return the value of item.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_id
     *
     * @param itemId the value for item.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_name
     *
     * @return the value of item.item_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_short_name
     *
     * @return the value of item.item_short_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemShortName() {
        return itemShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_short_name
     *
     * @param itemShortName the value for item.item_short_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemShortName(String itemShortName) {
        this.itemShortName = itemShortName == null ? null : itemShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_category
     *
     * @return the value of item.item_category
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemCategory() {
        return itemCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_category
     *
     * @param itemCategory the value for item.item_category
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory == null ? null : itemCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_kind1
     *
     * @return the value of item.item_kind1
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemKind1() {
        return itemKind1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_kind1
     *
     * @param itemKind1 the value for item.item_kind1
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemKind1(String itemKind1) {
        this.itemKind1 = itemKind1 == null ? null : itemKind1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_kind2
     *
     * @return the value of item.item_kind2
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemKind2() {
        return itemKind2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_kind2
     *
     * @param itemKind2 the value for item.item_kind2
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemKind2(String itemKind2) {
        this.itemKind2 = itemKind2 == null ? null : itemKind2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_kind3
     *
     * @return the value of item.item_kind3
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemKind3() {
        return itemKind3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_kind3
     *
     * @param itemKind3 the value for item.item_kind3
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemKind3(String itemKind3) {
        this.itemKind3 = itemKind3 == null ? null : itemKind3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_detail
     *
     * @return the value of item.item_detail
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemDetail() {
        return itemDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_detail
     *
     * @param itemDetail the value for item.item_detail
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemDetail(String itemDetail) {
        this.itemDetail = itemDetail == null ? null : itemDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.insert_user_id
     *
     * @return the value of item.insert_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.insert_user_id
     *
     * @param insertUserId the value for item.insert_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.insert_datetime
     *
     * @return the value of item.insert_datetime
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.insert_datetime
     *
     * @param insertDatetime the value for item.insert_datetime
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_user_id
     *
     * @return the value of item.update_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_user_id
     *
     * @param updateUserId the value for item.update_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_datetime
     *
     * @return the value of item.update_datetime
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_datetime
     *
     * @param updateDatetime the value for item.update_datetime
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.deleted
     *
     * @return the value of item.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.deleted
     *
     * @param deleted the value for item.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}