package com.next.model;

public class ItemPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_photo.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_photo.item_photo
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String itemPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_photo.photo_order
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer photoOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_photo.photo_link
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String photoLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_photo.item_id
     *
     * @return the value of item_photo.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_photo.item_id
     *
     * @param itemId the value for item_photo.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_photo.item_photo
     *
     * @return the value of item_photo.item_photo
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getItemPhoto() {
        return itemPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_photo.item_photo
     *
     * @param itemPhoto the value for item_photo.item_photo
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemPhoto(String itemPhoto) {
        this.itemPhoto = itemPhoto == null ? null : itemPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_photo.photo_order
     *
     * @return the value of item_photo.photo_order
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getPhotoOrder() {
        return photoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_photo.photo_order
     *
     * @param photoOrder the value for item_photo.photo_order
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPhotoOrder(Integer photoOrder) {
        this.photoOrder = photoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_photo.photo_link
     *
     * @return the value of item_photo.photo_link
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getPhotoLink() {
        return photoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_photo.photo_link
     *
     * @param photoLink the value for item_photo.photo_link
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPhotoLink(String photoLink) {
        this.photoLink = photoLink == null ? null : photoLink.trim();
    }
}