package com.next.model;

import java.math.BigDecimal;

public class ItemPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.item_price_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer itemPriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.selling_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private BigDecimal sellingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.discount_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private BigDecimal discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.discount_rate
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.discount_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String discountStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.discount_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String discountEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.selling_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String sellingStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.selling_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String sellingEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.selling_location
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String sellingLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_price.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.item_price_id
     *
     * @return the value of item_price.item_price_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getItemPriceId() {
        return itemPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.item_price_id
     *
     * @param itemPriceId the value for item_price.item_price_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemPriceId(Integer itemPriceId) {
        this.itemPriceId = itemPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.item_id
     *
     * @return the value of item_price.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.item_id
     *
     * @param itemId the value for item_price.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.selling_price
     *
     * @return the value of item_price.selling_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public BigDecimal getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.selling_price
     *
     * @param sellingPrice the value for item_price.selling_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.discount_price
     *
     * @return the value of item_price.discount_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.discount_price
     *
     * @param discountPrice the value for item_price.discount_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.discount_rate
     *
     * @return the value of item_price.discount_rate
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.discount_rate
     *
     * @param discountRate the value for item_price.discount_rate
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.discount_start_date
     *
     * @return the value of item_price.discount_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getDiscountStartDate() {
        return discountStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.discount_start_date
     *
     * @param discountStartDate the value for item_price.discount_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDiscountStartDate(String discountStartDate) {
        this.discountStartDate = discountStartDate == null ? null : discountStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.discount_end_date
     *
     * @return the value of item_price.discount_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getDiscountEndDate() {
        return discountEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.discount_end_date
     *
     * @param discountEndDate the value for item_price.discount_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDiscountEndDate(String discountEndDate) {
        this.discountEndDate = discountEndDate == null ? null : discountEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.selling_start_date
     *
     * @return the value of item_price.selling_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getSellingStartDate() {
        return sellingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.selling_start_date
     *
     * @param sellingStartDate the value for item_price.selling_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setSellingStartDate(String sellingStartDate) {
        this.sellingStartDate = sellingStartDate == null ? null : sellingStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.selling_end_date
     *
     * @return the value of item_price.selling_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getSellingEndDate() {
        return sellingEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.selling_end_date
     *
     * @param sellingEndDate the value for item_price.selling_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setSellingEndDate(String sellingEndDate) {
        this.sellingEndDate = sellingEndDate == null ? null : sellingEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.selling_location
     *
     * @return the value of item_price.selling_location
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getSellingLocation() {
        return sellingLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.selling_location
     *
     * @param sellingLocation the value for item_price.selling_location
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setSellingLocation(String sellingLocation) {
        this.sellingLocation = sellingLocation == null ? null : sellingLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_price.deleted
     *
     * @return the value of item_price.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_price.deleted
     *
     * @param deleted the value for item_price.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}