package com.next.model;

import java.math.BigDecimal;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchase_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.supplier_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchase_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchase_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private BigDecimal purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchase_count
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer purchaseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchase_id
     *
     * @return the value of purchase.purchase_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchase_id
     *
     * @param purchaseId the value for purchase.purchase_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.supplier_id
     *
     * @return the value of purchase.supplier_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.supplier_id
     *
     * @param supplierId the value for purchase.supplier_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.item_id
     *
     * @return the value of purchase.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.item_id
     *
     * @param itemId the value for purchase.item_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchase_date
     *
     * @return the value of purchase.purchase_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchase_date
     *
     * @param purchaseDate the value for purchase.purchase_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPurchaseDate(String purchaseDate) {
        this.purchaseDate = purchaseDate == null ? null : purchaseDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchase_price
     *
     * @return the value of purchase.purchase_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public BigDecimal getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchase_price
     *
     * @param purchasePrice the value for purchase.purchase_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPurchasePrice(BigDecimal purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchase_count
     *
     * @return the value of purchase.purchase_count
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getPurchaseCount() {
        return purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchase_count
     *
     * @param purchaseCount the value for purchase.purchase_count
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPurchaseCount(Integer purchaseCount) {
        this.purchaseCount = purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.deleted
     *
     * @return the value of purchase.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.deleted
     *
     * @param deleted the value for purchase.deleted
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}