package com.next.model;

public class UserLp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.user_role
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.use_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String useStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.use_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String useEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.approval_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String approvalUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.approval_status
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_lp.approval_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String approvalDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.user_id
     *
     * @return the value of user_lp.user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.user_id
     *
     * @param userId the value for user_lp.user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.user_role
     *
     * @return the value of user_lp.user_role
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.user_role
     *
     * @param userRole the value for user_lp.user_role
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.use_start_date
     *
     * @return the value of user_lp.use_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUseStartDate() {
        return useStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.use_start_date
     *
     * @param useStartDate the value for user_lp.use_start_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUseStartDate(String useStartDate) {
        this.useStartDate = useStartDate == null ? null : useStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.use_end_date
     *
     * @return the value of user_lp.use_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUseEndDate() {
        return useEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.use_end_date
     *
     * @param useEndDate the value for user_lp.use_end_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUseEndDate(String useEndDate) {
        this.useEndDate = useEndDate == null ? null : useEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.approval_user_id
     *
     * @return the value of user_lp.approval_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getApprovalUserId() {
        return approvalUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.approval_user_id
     *
     * @param approvalUserId the value for user_lp.approval_user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setApprovalUserId(String approvalUserId) {
        this.approvalUserId = approvalUserId == null ? null : approvalUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.approval_status
     *
     * @return the value of user_lp.approval_status
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.approval_status
     *
     * @param approvalStatus the value for user_lp.approval_status
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_lp.approval_date
     *
     * @return the value of user_lp.approval_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_lp.approval_date
     *
     * @param approvalDate the value for user_lp.approval_date
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setApprovalDate(String approvalDate) {
        this.approvalDate = approvalDate == null ? null : approvalDate.trim();
    }
}