package com.next.dao;

import com.next.model.ItemPrice;
import com.next.model.ItemPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int countByExample(ItemPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int deleteByExample(ItemPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int deleteByPrimaryKey(Integer itemPriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int insert(ItemPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int insertSelective(ItemPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    List<ItemPrice> selectByExample(ItemPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    ItemPrice selectByPrimaryKey(Integer itemPriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int updateByExampleSelective(@Param("record") ItemPrice record, @Param("example") ItemPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int updateByExample(@Param("record") ItemPrice record, @Param("example") ItemPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int updateByPrimaryKeySelective(ItemPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_price
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int updateByPrimaryKey(ItemPrice record);
}