package com.next.dao;

import com.next.model.UserLp;
import com.next.model.UserLpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int countByExample(UserLpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int deleteByExample(UserLpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int insert(UserLp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int insertSelective(UserLp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    List<UserLp> selectByExample(UserLpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int updateByExampleSelective(@Param("record") UserLp record, @Param("example") UserLpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_lp
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    int updateByExample(@Param("record") UserLp record, @Param("example") UserLpExample example);
}