package com.next.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_post_no
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String customerPostNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_address
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.payment_type
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.postsend_type
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String postsendType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_post_no
     *
     * @return the value of customer.customer_post_no
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getCustomerPostNo() {
        return customerPostNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_post_no
     *
     * @param customerPostNo the value for customer.customer_post_no
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setCustomerPostNo(String customerPostNo) {
        this.customerPostNo = customerPostNo == null ? null : customerPostNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_address
     *
     * @return the value of customer.customer_address
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_address
     *
     * @param customerAddress the value for customer.customer_address
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.payment_type
     *
     * @return the value of customer.payment_type
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.payment_type
     *
     * @param paymentType the value for customer.payment_type
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.postsend_type
     *
     * @return the value of customer.postsend_type
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getPostsendType() {
        return postsendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.postsend_type
     *
     * @param postsendType the value for customer.postsend_type
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setPostsendType(String postsendType) {
        this.postsendType = postsendType == null ? null : postsendType.trim();
    }
}