package com.next.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public ItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameIsNull() {
            addCriterion("item_short_name is null");
            return (Criteria) this;
        }

        public Criteria andItemShortNameIsNotNull() {
            addCriterion("item_short_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemShortNameEqualTo(String value) {
            addCriterion("item_short_name =", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameNotEqualTo(String value) {
            addCriterion("item_short_name <>", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameGreaterThan(String value) {
            addCriterion("item_short_name >", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_short_name >=", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameLessThan(String value) {
            addCriterion("item_short_name <", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameLessThanOrEqualTo(String value) {
            addCriterion("item_short_name <=", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameLike(String value) {
            addCriterion("item_short_name like", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameNotLike(String value) {
            addCriterion("item_short_name not like", value, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameIn(List<String> values) {
            addCriterion("item_short_name in", values, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameNotIn(List<String> values) {
            addCriterion("item_short_name not in", values, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameBetween(String value1, String value2) {
            addCriterion("item_short_name between", value1, value2, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemShortNameNotBetween(String value1, String value2) {
            addCriterion("item_short_name not between", value1, value2, "itemShortName");
            return (Criteria) this;
        }

        public Criteria andItemCategoryIsNull() {
            addCriterion("item_category is null");
            return (Criteria) this;
        }

        public Criteria andItemCategoryIsNotNull() {
            addCriterion("item_category is not null");
            return (Criteria) this;
        }

        public Criteria andItemCategoryEqualTo(String value) {
            addCriterion("item_category =", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryNotEqualTo(String value) {
            addCriterion("item_category <>", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryGreaterThan(String value) {
            addCriterion("item_category >", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("item_category >=", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryLessThan(String value) {
            addCriterion("item_category <", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryLessThanOrEqualTo(String value) {
            addCriterion("item_category <=", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryLike(String value) {
            addCriterion("item_category like", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryNotLike(String value) {
            addCriterion("item_category not like", value, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryIn(List<String> values) {
            addCriterion("item_category in", values, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryNotIn(List<String> values) {
            addCriterion("item_category not in", values, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryBetween(String value1, String value2) {
            addCriterion("item_category between", value1, value2, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemCategoryNotBetween(String value1, String value2) {
            addCriterion("item_category not between", value1, value2, "itemCategory");
            return (Criteria) this;
        }

        public Criteria andItemKind1IsNull() {
            addCriterion("item_kind1 is null");
            return (Criteria) this;
        }

        public Criteria andItemKind1IsNotNull() {
            addCriterion("item_kind1 is not null");
            return (Criteria) this;
        }

        public Criteria andItemKind1EqualTo(String value) {
            addCriterion("item_kind1 =", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1NotEqualTo(String value) {
            addCriterion("item_kind1 <>", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1GreaterThan(String value) {
            addCriterion("item_kind1 >", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1GreaterThanOrEqualTo(String value) {
            addCriterion("item_kind1 >=", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1LessThan(String value) {
            addCriterion("item_kind1 <", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1LessThanOrEqualTo(String value) {
            addCriterion("item_kind1 <=", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1Like(String value) {
            addCriterion("item_kind1 like", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1NotLike(String value) {
            addCriterion("item_kind1 not like", value, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1In(List<String> values) {
            addCriterion("item_kind1 in", values, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1NotIn(List<String> values) {
            addCriterion("item_kind1 not in", values, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1Between(String value1, String value2) {
            addCriterion("item_kind1 between", value1, value2, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind1NotBetween(String value1, String value2) {
            addCriterion("item_kind1 not between", value1, value2, "itemKind1");
            return (Criteria) this;
        }

        public Criteria andItemKind2IsNull() {
            addCriterion("item_kind2 is null");
            return (Criteria) this;
        }

        public Criteria andItemKind2IsNotNull() {
            addCriterion("item_kind2 is not null");
            return (Criteria) this;
        }

        public Criteria andItemKind2EqualTo(String value) {
            addCriterion("item_kind2 =", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2NotEqualTo(String value) {
            addCriterion("item_kind2 <>", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2GreaterThan(String value) {
            addCriterion("item_kind2 >", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2GreaterThanOrEqualTo(String value) {
            addCriterion("item_kind2 >=", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2LessThan(String value) {
            addCriterion("item_kind2 <", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2LessThanOrEqualTo(String value) {
            addCriterion("item_kind2 <=", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2Like(String value) {
            addCriterion("item_kind2 like", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2NotLike(String value) {
            addCriterion("item_kind2 not like", value, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2In(List<String> values) {
            addCriterion("item_kind2 in", values, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2NotIn(List<String> values) {
            addCriterion("item_kind2 not in", values, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2Between(String value1, String value2) {
            addCriterion("item_kind2 between", value1, value2, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind2NotBetween(String value1, String value2) {
            addCriterion("item_kind2 not between", value1, value2, "itemKind2");
            return (Criteria) this;
        }

        public Criteria andItemKind3IsNull() {
            addCriterion("item_kind3 is null");
            return (Criteria) this;
        }

        public Criteria andItemKind3IsNotNull() {
            addCriterion("item_kind3 is not null");
            return (Criteria) this;
        }

        public Criteria andItemKind3EqualTo(String value) {
            addCriterion("item_kind3 =", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3NotEqualTo(String value) {
            addCriterion("item_kind3 <>", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3GreaterThan(String value) {
            addCriterion("item_kind3 >", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3GreaterThanOrEqualTo(String value) {
            addCriterion("item_kind3 >=", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3LessThan(String value) {
            addCriterion("item_kind3 <", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3LessThanOrEqualTo(String value) {
            addCriterion("item_kind3 <=", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3Like(String value) {
            addCriterion("item_kind3 like", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3NotLike(String value) {
            addCriterion("item_kind3 not like", value, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3In(List<String> values) {
            addCriterion("item_kind3 in", values, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3NotIn(List<String> values) {
            addCriterion("item_kind3 not in", values, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3Between(String value1, String value2) {
            addCriterion("item_kind3 between", value1, value2, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemKind3NotBetween(String value1, String value2) {
            addCriterion("item_kind3 not between", value1, value2, "itemKind3");
            return (Criteria) this;
        }

        public Criteria andItemDetailIsNull() {
            addCriterion("item_detail is null");
            return (Criteria) this;
        }

        public Criteria andItemDetailIsNotNull() {
            addCriterion("item_detail is not null");
            return (Criteria) this;
        }

        public Criteria andItemDetailEqualTo(String value) {
            addCriterion("item_detail =", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailNotEqualTo(String value) {
            addCriterion("item_detail <>", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailGreaterThan(String value) {
            addCriterion("item_detail >", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailGreaterThanOrEqualTo(String value) {
            addCriterion("item_detail >=", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailLessThan(String value) {
            addCriterion("item_detail <", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailLessThanOrEqualTo(String value) {
            addCriterion("item_detail <=", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailLike(String value) {
            addCriterion("item_detail like", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailNotLike(String value) {
            addCriterion("item_detail not like", value, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailIn(List<String> values) {
            addCriterion("item_detail in", values, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailNotIn(List<String> values) {
            addCriterion("item_detail not in", values, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailBetween(String value1, String value2) {
            addCriterion("item_detail between", value1, value2, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andItemDetailNotBetween(String value1, String value2) {
            addCriterion("item_detail not between", value1, value2, "itemDetail");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("insert_user_id is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("insert_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("insert_user_id =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("insert_user_id <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("insert_user_id >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("insert_user_id >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("insert_user_id <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("insert_user_id <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("insert_user_id like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("insert_user_id not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("insert_user_id in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("insert_user_id not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("insert_user_id between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("insert_user_id not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNull() {
            addCriterion("insert_datetime is null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNotNull() {
            addCriterion("insert_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeEqualTo(Date value) {
            addCriterion("insert_datetime =", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotEqualTo(Date value) {
            addCriterion("insert_datetime <>", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThan(Date value) {
            addCriterion("insert_datetime >", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_datetime >=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThan(Date value) {
            addCriterion("insert_datetime <", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("insert_datetime <=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIn(List<Date> values) {
            addCriterion("insert_datetime in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotIn(List<Date> values) {
            addCriterion("insert_datetime not in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeBetween(Date value1, Date value2) {
            addCriterion("insert_datetime between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(Date value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(Date value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(Date value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(Date value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<Date> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<Date> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(Date value1, Date value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 10 19:51:27 JST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}