package com.next.model;

import java.util.ArrayList;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNull() {
            addCriterion("user_address is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNotNull() {
            addCriterion("user_address is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressEqualTo(String value) {
            addCriterion("user_address =", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotEqualTo(String value) {
            addCriterion("user_address <>", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThan(String value) {
            addCriterion("user_address >", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("user_address >=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThan(String value) {
            addCriterion("user_address <", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThanOrEqualTo(String value) {
            addCriterion("user_address <=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLike(String value) {
            addCriterion("user_address like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotLike(String value) {
            addCriterion("user_address not like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressIn(List<String> values) {
            addCriterion("user_address in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotIn(List<String> values) {
            addCriterion("user_address not in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressBetween(String value1, String value2) {
            addCriterion("user_address between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotBetween(String value1, String value2) {
            addCriterion("user_address not between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserPostNoIsNull() {
            addCriterion("user_post_no is null");
            return (Criteria) this;
        }

        public Criteria andUserPostNoIsNotNull() {
            addCriterion("user_post_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserPostNoEqualTo(String value) {
            addCriterion("user_post_no =", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoNotEqualTo(String value) {
            addCriterion("user_post_no <>", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoGreaterThan(String value) {
            addCriterion("user_post_no >", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_post_no >=", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoLessThan(String value) {
            addCriterion("user_post_no <", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoLessThanOrEqualTo(String value) {
            addCriterion("user_post_no <=", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoLike(String value) {
            addCriterion("user_post_no like", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoNotLike(String value) {
            addCriterion("user_post_no not like", value, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoIn(List<String> values) {
            addCriterion("user_post_no in", values, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoNotIn(List<String> values) {
            addCriterion("user_post_no not in", values, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoBetween(String value1, String value2) {
            addCriterion("user_post_no between", value1, value2, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserPostNoNotBetween(String value1, String value2) {
            addCriterion("user_post_no not between", value1, value2, "userPostNo");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneIsNull() {
            addCriterion("user_mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneIsNotNull() {
            addCriterion("user_mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneEqualTo(String value) {
            addCriterion("user_mobile_phone =", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneNotEqualTo(String value) {
            addCriterion("user_mobile_phone <>", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneGreaterThan(String value) {
            addCriterion("user_mobile_phone >", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_mobile_phone >=", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneLessThan(String value) {
            addCriterion("user_mobile_phone <", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("user_mobile_phone <=", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneLike(String value) {
            addCriterion("user_mobile_phone like", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneNotLike(String value) {
            addCriterion("user_mobile_phone not like", value, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneIn(List<String> values) {
            addCriterion("user_mobile_phone in", values, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneNotIn(List<String> values) {
            addCriterion("user_mobile_phone not in", values, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneBetween(String value1, String value2) {
            addCriterion("user_mobile_phone between", value1, value2, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("user_mobile_phone not between", value1, value2, "userMobilePhone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneIsNull() {
            addCriterion("user_telphone is null");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneIsNotNull() {
            addCriterion("user_telphone is not null");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneEqualTo(String value) {
            addCriterion("user_telphone =", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotEqualTo(String value) {
            addCriterion("user_telphone <>", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneGreaterThan(String value) {
            addCriterion("user_telphone >", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_telphone >=", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneLessThan(String value) {
            addCriterion("user_telphone <", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneLessThanOrEqualTo(String value) {
            addCriterion("user_telphone <=", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneLike(String value) {
            addCriterion("user_telphone like", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotLike(String value) {
            addCriterion("user_telphone not like", value, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneIn(List<String> values) {
            addCriterion("user_telphone in", values, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotIn(List<String> values) {
            addCriterion("user_telphone not in", values, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneBetween(String value1, String value2) {
            addCriterion("user_telphone between", value1, value2, "userTelphone");
            return (Criteria) this;
        }

        public Criteria andUserTelphoneNotBetween(String value1, String value2) {
            addCriterion("user_telphone not between", value1, value2, "userTelphone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 10 19:51:27 JST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}