package com.next.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_address
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_post_no
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userPostNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_mobile_phone
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userMobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_telphone
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    private String userTelphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_address
     *
     * @return the value of user_info.user_address
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_address
     *
     * @param userAddress the value for user_info.user_address
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_post_no
     *
     * @return the value of user_info.user_post_no
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserPostNo() {
        return userPostNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_post_no
     *
     * @param userPostNo the value for user_info.user_post_no
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserPostNo(String userPostNo) {
        this.userPostNo = userPostNo == null ? null : userPostNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_mobile_phone
     *
     * @return the value of user_info.user_mobile_phone
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserMobilePhone() {
        return userMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_mobile_phone
     *
     * @param userMobilePhone the value for user_info.user_mobile_phone
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserMobilePhone(String userMobilePhone) {
        this.userMobilePhone = userMobilePhone == null ? null : userMobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_telphone
     *
     * @return the value of user_info.user_telphone
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public String getUserTelphone() {
        return userTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_telphone
     *
     * @param userTelphone the value for user_info.user_telphone
     *
     * @mbggenerated Sun Mar 10 19:51:27 JST 2013
     */
    public void setUserTelphone(String userTelphone) {
        this.userTelphone = userTelphone == null ? null : userTelphone.trim();
    }
}